React tutorial
Koya-SI/React pull request #4
Opened 2020-12-10 01:45 UTC by Koya-SI

README.mdとgame.jsの不要な改行を削除しました。

2020-12-10 04:09 UTC, InoueKenichi requested changes
説明がたらない部分がありましたので、再考してみてください。

2020-12-10 04:09 UTC, InoueKenichi commented on README.md
> +			- コンストラクターでステートの初期値が入る
どういう種類の初期値が入るのでしょうか？

2020-12-10 04:09 UTC, InoueKenichi commented on README.md
> +			- render関数が呼ばれ、その中で定義した変数に値が入る
どの変数に何の値が入るのでしょうか？

2020-12-10 04:09 UTC, InoueKenichi commented on README.md
> +			- returnでBoardクラスが呼ばれる
どのretrurnを指しているのでしょうか。
https://github.com/Koya-SI/React/blob/main/my-app/src/components/game/game.js#L50？
https://github.com/Koya-SI/React/blob/main/my-app/src/components/game/game.js#L64？

2020-12-10 04:09 UTC, InoueKenichi commented on README.md
> +			- returnでBoardクラスが呼ばれる
https://github.com/Koya-SI/React/blob/main/my-app/src/components/game/game.js#L57-L62
こちらでは何をしていますか？

2020-12-10 04:09 UTC, InoueKenichi commented on README.md
> +			- returnでBoardクラスが呼ばれる
https://github.com/Koya-SI/React/blob/main/my-app/src/components/game/game.js#L72-L76
こちらでは何をしていますか？

2020-12-10 04:09 UTC, InoueKenichi commented on README.md
> +			- render関数が呼ばれ、return内でrenderSquare関数を呼ぶ
renderなんて呼ばれていません。

2020-12-10 04:09 UTC, InoueKenichi commented on my-app/src/components/game/game.js
> +      console.log(this.state.history)
確認後は、パフォーマンスの悪化もありますので、削除するようにしてください。
ライブラリの導入によっては、アプリケーション実行時にログを吐かないように設定をすることができますが。
今回は、導入していないのでPRを出す際には、削除するようにしましょう。

2020-12-14 01:16 UTC, InoueKenichi commented
こちらのPRは閉じますか？

2020-12-14 01:42 UTC, Koya-SI commented
閉じてもらって大丈夫です。

2020-12-14 01:45 UTC, closed without merging