WIP: React tutorial
Koya-SI/React pull request #5
Opened 2020-12-10 08:21 UTC by Koya-SI

コミット内容の詳細
TypeScriptに書き直すためのモジュールをインストールしました。

2020-12-10 08:34 UTC, InoueKenichi requested changes
　コメントを追加しました。

2020-12-10 08:34 UTC, InoueKenichi commented on my-app/package.json
>    "scripts": {
@types/react
@types/react-dom
を型定義として導入する必要があると思います。

2020-12-10 08:34 UTC, InoueKenichi commented on my-app/src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
自分で型定義は定義しなくてもよいと思います。

2020-12-14 01:15 UTC, InoueKenichi commented
こちらのPR閉じます？

2020-12-14 01:41 UTC, merged

2020-12-14 01:42 UTC, Koya-SI commented
こちらも閉じてもらって大丈夫です。